=pod

=head1 NAME

Dist::Zilla::Plugin::RequiresExternal - make dists require external commands

=head1 VERSION

version 0.110480

=head1 SYNOPSIS

=head1 DESCRIPTION

This L<Dist::Zilla|Dist::Zilla> plugin creates a test in your distribution
to check for the existence of executable commands you require.

=head1 ATTRIBUTES

=head2 requires

Each C<requires> attribute should be either a full path to an executable or
the name of a command in the user's C<PATH> environment.

=head1 METHODS

=head2 gather_files

Adds a F<t/requires_external.t> test script to the distribution that checks
if each L</requires> item is executable.
Required by
L<Dist::Zilla::Role::FileGatherer|Dist::Zilla::Role::FileGatherer>.

=head2 metadata

Using this plugin will add the L<Env::Path|Env::Path> to your distribution's
testing prerequisites, since it uses that module to look for executables in
the user's C<PATH>.

=encoding utf8

=for Pod::Coverage mvp_multivalue_args

=for test_synopsis 1;

=for test_synopsis __END__

In your F<dist.ini>:

    [RequiresExternal]
    requires = /path/to/some/executable
    requires = executable_in_path

=head1 AUTHOR

Mark Gardner <mjgardner@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Mark Gardner.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

